---
dist: bionic
services: docker

env:
  - IMAGE_NAME='infrastructr/scratch'

script:
  - docker build . -t "$IMAGE_NAME:$TRAVIS_BRANCH" -t "$IMAGE_NAME:latest" --build-arg MAGENTO_PUBLIC_KEY="$MAGENTO_PUBLIC_KEY" --build-arg MAGENTO_PRIVATE_KEY="$MAGENTO_PRIVATE_KEY"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$TRAVIS_BRANCH" && docker push "$IMAGE_NAME:latest"
